### ISSUE TITLE
Add ownCloud (or webDav) support

### ISSUE THREAD

**Issue by JuniorJPDJ** [viciousviper/CloudFS#11]
There are some public services offering ownCloud access (https://owncloud.org/providers/)
It is also self hosted and imho the best opensource cloud.
https://github.com/bnoffer/owncloud-sharp
There is great library for c#

**Comment by viciousviper** [comment]
Looks ok at first inspection.
You wouldn't know if one of the listed providers offers >= 10GB free storage space quota as listed in the CloudFS prerequisites?

**Comment by JuniorJPDJ** [comment]
I don't know, I'm hosting it at myself.
But I'll take a look

**Comment by JuniorJPDJ** [comment]
https://www.tucloudserver.com/console/cart.php?gid=6
This one is :D

**Comment by viciousviper** [comment]
Hi @JuniorJPDJ,

I just committed preliminary WebDAV support with 23195b17 on a feature branch if you'd like to take an early look. The WebDAV gateway completed the CloudFS test suite successfully on a non-OneCloud hoster (German Telekom MagentaCloud) and a public OneCloud-based hoster from your list (oCloud.de).

I'm not ready to release this code just yet because the login credentials can't be persisted until the config encryption feature requested in https://github.com/viciousviper/DokanCloudFS/issues/17 is in place - which means that you'll have to re-authenticate via the login form each time the WebDAV gateway is instantiated.

However, I'd certainly value your feedback on the general suitability of the WebDAV gateway for self-hosted OneCloud environments.

BTW, apparently none of WebDAV interfaces of the large cloud providers implements quota information via `quota-available-bytes` and `quota-used-bytes` while the OCloud-based provider did. Is there another established quota scheme I should support or do they just suck?

**Comment by viciousviper** [comment]
Fixed in ef512681.
